### ISSUE TITLE
【接口】希望大佬能更新一下接口文档，或者接口简略的返回格式数据也行，服务挂了看不到了

### ISSUE THREAD

**Issue by Jizishuo** [aquanlerou/WeHalo#100]
希望大佬能更新一下接口文档，或者接口简略的返回格式数据也行，服务挂了看不到了
【https://aquan.run/api/content】
![image](https://github.com/user-attachments/assets/7dd5d991-db8f-42fb-9083-3bdef55f7bdd)

**Comment by sav7ng** [comment]
@Jizishuo 这个是我的服务器地址，你需要换成你自己的服务器噢

**Comment by Jizishuo** [comment]
### 

> @Jizishuo这是我的服务器地址，你需要换成你自己的服务器哦

可以换成自己的服务器的 ，但是不晓得 接口返回的数据格式是啥，所以希望大佬有返回接口的 json ，或者简略的接口稳定也行

**Comment by sav7ng** [comment]
@Jizishuo 你可以单独用post慢请求一下，就可以获取到返回的json数据了

**Comment by Jizishuo** [comment]
> @Jizishuo 你可以单独用post慢请求一下，就可以获取到返回的json数据了

[http://aquan.run】大佬 服务器 post 不通了

**Comment by sav7ng** [comment]
@Jizishuo 用你自己的服务器噢，这个是我的服务器
