### ISSUE TITLE
Wish to adapt halo v1.0

### ISSUE THREAD

**Issue by JohnNiang** [aquanlerou/WeHalo#16]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by aquanlerou** [comment]
@JohnNiang No problem!

**Comment by VangelisHaha** [comment]
万人血书求 支持`1.0`

**Comment by aquanlerou** [comment]
@VangelisHaha 这有点夸张了，收到，看了大家都很急 ~

**Comment by ruibaby** [comment]
等不及了

**Comment by VangelisHaha** [comment]
今天是2019-07-22，催更打卡

**Comment by aquanlerou** [comment]
@VangelisHaha 厉害了

**Comment by VangelisHaha** [comment]
> 今天是2019-08-04，催更打卡

**Comment by JohnNiang** [comment]
> > 今天是2019-08-04，催更打卡

Comming...

**Comment by aquanlerou** [comment]
@VangelisHaha @JohnNiang 已经在dev分支中啦，还在开发调试中

**Comment by VangelisHaha** [comment]
收到

**Comment by aquanlerou** [comment]
@VangelisHaha @JohnNiang @ruibaby 
WeHalo新版本已发布~~~~~
