### ISSUE TITLE
小程序调用接口404，应该如何设置

### ISSUE THREAD

**Issue by sukaihua** [aquanlerou/WeHalo#21]
![image](https://user-images.githubusercontent.com/19904963/65298220-44ac4600-db9d-11e9-97e7-d285d1d89cbc.png)

**Comment by aquanlerou** [comment]
@sukaihua 您是否是用的是Halo_v1.x.x版本的呢，如果是的话那就等我这个星期吧dev支线中的代码合并到master中并写好新的README.md😁

**Comment by sukaihua** [comment]
嗯，好，谢谢
