### ISSUE TITLE
无法编译运行小程序，报错

### ISSUE THREAD

**Issue by mikutown** [aquanlerou/WeHalo#37]
如图
![image](https://user-images.githubusercontent.com/35498600/69333469-a1a6a400-0c93-11ea-98e3-480c1fe07d09.png)

**Comment by aquanlerou** [comment]
@mikutown 全局变量填上去了吗？

**Comment by mikutown** [comment]
不好意思，现在发现的是这个错误
![image](https://user-images.githubusercontent.com/35498600/69335484-07952a80-0c98-11ea-8cee-523321bc5589.png)

我不知道那个openid怎么获取，我在console里找不到。。

**Comment by mikutown** [comment]
一片姨妈红，心态要崩了

**Comment by mikutown** [comment]
我把微信的小程序appsecret填到配置文件和我的博客后台里了，但是现在还是不行

**Comment by mikutown** [comment]
![image](https://user-images.githubusercontent.com/35498600/69336349-41b2fc00-0c99-11ea-838a-35b07ebec3ee.png)
我的博客那里还是报401错误，然后还要我开通。。云服务？我有点搞不懂这个东西

**Comment by mikutown** [comment]
不好意思我 我是个特别菜的菜鸟😂要是问的问题太傻了可以不回答

**Comment by aquanlerou** [comment]
@mikutown 关于新版本WeHalo找不到adminOpenid的处理方法： https://gitee.com/Aquan_LeRou/WeHalo/issues/I12J1G

**Comment by aquanlerou** [comment]
@mikutown 没事的，你可以加qq群和群里的小伙伴一起讨论讨论

**Comment by mikutown** [comment]
收到



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Aquan"<notifications@github.com&gt;; 
发送时间: 2019年11月21日(星期四) 晚上8:16
收件人: "aquanlerou/WeHalo"<WeHalo@noreply.github.com&gt;; 
抄送: "西决"<503944896@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [aquanlerou/WeHalo] 无法编译运行小程序，报错 (#37)




@mikutown 关于新版本WeHalo找不到adminOpenid的处理方法： https://gitee.com/Aquan_LeRou/WeHalo/issues/I12J1G
