### ISSUE TITLE
重复访问两次

### ISSUE THREAD

**Issue by wenthywang** [aquanlerou/WeHalo#4]
![image](https://user-images.githubusercontent.com/15195159/50389426-2972ee00-0765-11e9-9a33-2678a0cf2fb3.png)

**Comment by aquanlerou** [comment]
我在测试封装的请求，和没封装的请求，还没全部封装好所以那个还没封装，在测试调试中，后面会推送新的代码解决这个问题。

**Comment by wenthywang** [comment]
@aquanlerou 但是一次请求怎么 也要6s？我的网络问题？

**Comment by aquanlerou** [comment]
[](https://blog.eunji.cn/upload/2018/11/TIM图片2018122414363720181224143720747.png) @wenthywang 
好像真的是网络问题，不过也不能排除服务器不在国内造成的延迟和接口返回数据量打的问题。

**Comment by wenthywang** [comment]
@aquanlerou 网络问题 ？我用的是腾讯的 国内的

**Comment by wenthywang** [comment]
文章转换成json 是在服务端 是不是很耗时？

**Comment by aquanlerou** [comment]
你ping下你的服务器看看延迟怎么样，这个存在数据库就是JSON的形式了。 @wenthywang

**Comment by wenthywang** [comment]
![image](https://user-images.githubusercontent.com/15195159/50394640-cf405000-0799-11e9-9d5b-aea4b20d7edd.png)
@aquanlerou   没毛病

**Comment by aquanlerou** [comment]
你试试用Postman在页面上单独输入访问下你的接口试试多久？ @wenthywang

**Comment by wenthywang** [comment]
![image](https://user-images.githubusercontent.com/15195159/50394823-02371380-079b-11e9-8f9e-8d089d451b16.png)
@aquanlerou  也要3s

**Comment by wenthywang** [comment]
配置问题？ 2g内存  docker 部署

**Comment by aquanlerou** [comment]
这么奇怪吗？我的服务器在韩国首尔加了cdn也比你这个快=。= @wenthywang ，请求接口我这边编写的是没问题的。

**Comment by wenthywang** [comment]
@aquanlerou 服务端是不是要配置什么的？不会是实时生成json 然后这么慢？你这个韩国也是6

**Comment by aquanlerou** [comment]
这个就不知道了=。=我也没配置什么呀。不过我不是docker部署的，应该不是这个问题。 @wenthywang

**Comment by wenthywang** [comment]
这就尴尬了  我搞个源码研究下吧
