### ISSUE TITLE
能不能发个针对  小白的教程啊  

### ISSUE THREAD

**Issue by riocwong** [aquanlerou/WeHalo#44]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by aquanlerou** [comment]
您要是遇到搭建问题可以添加QQ群：260050047 我都会在里面解答问题。也会给出学习的意见

**Comment by aquanlerou** [comment]
@riocwong
