### ISSUE TITLE
能不能支持云开发（服务器和后台维护的确是个麻烦的事情）

### ISSUE THREAD

**Issue by gooking** [aquanlerou/WeHalo#47]
现在小程序的云开发很流行，能不能搞一个支持云开发的版本？这样就不用自己买服务器，自己去鼓弄后台了，甚至域名和证书都不再需要了，岂不是非常的方便么？

老大可以考虑一下，现在比如微信自带的云开发、https://www.apicloud.com/ 、 https://www.it120.cc/  等好多都提供这种云开发的服务的~

**Comment by aquanlerou** [comment]
@gooking 这个我考虑到了，有这个方向的发展的意思，只是现在空闲时间少，更新有点慢。后面会往云开发看起

**Comment by gooking** [comment]
期待
