### ISSUE TITLE
非常感谢作者

### ISSUE THREAD

**Issue by lybtt** [aquanlerou/WeHalo#49]
## 期望：
1. 希望未来的版本能有文章的类别分类，本人直男审美不知道加在哪里好，就先不弄了。。。

## ps
基于WeHalo的个人微信小程序刚刚申请上线了，名字：编程挺好玩。:smile:
在克隆下来的代码的基础上，做了些许细节上的改动，一些细节可以讨论下：
1. 我把index页面和hola页面上利用getStorageSync和setStorageSync 保存了用户的openid，这样在一定程度上可以减少云函数的调用。
2. 点赞，也是利用getStorageSync和setStorageSync 保存了用户是否点赞了该文章，调用halo 的接口实现likes+1（不过这个可以使用云开发的数据库来保存单篇文章所有的点赞用户，然后文章界面可以显示一排谁谁谁点赞了这篇文章，头像之类的）。

**Comment by lybtt** [comment]
:joy: 吐槽一下，审核小姐姐在文章下面回复了某个大人物的名字来测试。

**Comment by aquanlerou** [comment]
@lybtt 谢谢支持，我会继续改进的！
