### ISSUE TITLE
关于管理员的问题

### ISSUE THREAD

**Issue by ufec** [aquanlerou/WeHalo#59]
在miniprogram\pages\index\index.js里的第116行处，云函数获取用户openID，作者写的是res.result.openid，应该是写错了，正确的：res.result.userInfo.openId，导致无法识别管理员，后面还有类似几处错误，可直接批量修改

**Comment by aquanlerou** [comment]
@Chirmis 有待进一步观察，你云函数返回的格式比较特殊。影响识别管理员的情况，可能是云函数调用的异步同步问题，先赋的值，后执行的云函数。导致openId可空的原因
