### ISSUE TITLE
七牛云OSS启用后缩略图地址出错

### ISSUE THREAD

**Issue by slwl** [aquanlerou/WeHalo#6]
图片地址会多一个网址，导致图片地址错误，小程序端首页无法显示图片。

**Comment by aquanlerou** [comment]
@slwl 问题处理中

**Comment by proxygit** [comment]
这个可以尝试去掉了首页的图片略缩图路径前面的{{imageUrl}}，。但是我的文章内部的图片必须修改为绝对路径才行。
