### ISSUE TITLE
小程序增加点赞功能的方法

### ISSUE THREAD

**Issue by hgmsq** [aquanlerou/WeHalo#71]
只需要在post.js 增加以下方法就可以了

    //点赞功能
    Likes: function () {
        var that = this;
        var urlLikeList = app.globalData.url + '/api/content/posts/'+that.data.postId+'/likes';
        var token = app.globalData.token;
        var params = {            
        };
        //@todo 网络请求API数据
        request.requestPostApi(urlLikeList, token, params, this, this.successSendLike, this.failSendLike);  
    },
    // 点赞成功回调
    successSendLike: function (res, selfObj) {
        var that = this;        
        wx.showToast({
            title: '感谢你的点赞！',
            icon: 'none',
            duration: 2000
        });
        // 设置点赞数+1
        var likes = Number(parseInt(that.data.postLikes) + 1);   
        console.log(likes);
        that.setData({
             postLikes: likes       
        })
    },
    //点赞失败回调
    failSendLike: function (res, selfObj) {
        wx.showToast({
            title: '点赞失败，请联系作者！',
            icon: 'none',
            duration: 2000
        })
    },

小程序名称：IT技术分享社区
[IT技术分享社区](https://programmerblog.xyz/)
![gh_32334eb097cd_430](https://programmerblog.xyz/upload/2020/06/%E5%B0%8F%E7%A8%8B%E5%BA%8Flogo-27dc5136e7a64feeb693c4961c85e1da-thumbnail.jpg)

**Comment by aquanlerou** [comment]
感谢贡献代码~
