### ISSUE TITLE
如何部署呢？是云开发吗？

### ISSUE THREAD

**Issue by cnscorpions** [aquanlerou/WeHalo#78]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by aquanlerou** [comment]
B站部署视频： https://www.bilibili.com/video/BV1s5411Y7Pp/

**Comment by aquanlerou** [comment]
@cnscorpions B站部署视频： https://www.bilibili.com/video/BV1s5411Y7Pp/
用到了云开发相关接口，不是纯云开发。

**Comment by cnscorpions** [comment]
建议在文档中留这一句
